### ISSUE TITLE
Find a cool name for solus-sc

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#100]
Solus has some great-sounding names for software developed in-house (most recently ferryd). The current name is not very attractive by:
- its use of a hyphen
- repeating the name of the OS
- its use of an abbreviation
- its use of the 'software center or app store' metaphor which is boring and over-used

If approved, let the brainstorming begin ...

**Comment by ikeydoherty** [comment]
> its use of the 'software center or app store' metaphor which is boring and over-used

But that's exactly what it is. And I've tried coming up with names, but "Software Center" is what it is. "solus-sc" is just an internal codename.

Gonna close this as nobody has suggestions

**Comment by baimafeima** [comment]
@ikeydoherty Not on G+ so commenting here. How about:

- **orbit/orbiter** (avian theme, in-house developed and external software orbiting the software center)
- **hotpot** (the crew can't stay hungry, ingredients aka packages get bundled together to create good dishes, deployed on the local computers)
- **skipper** (nautical theme, go to the skipper if you need something)
- **anchor** (nautical theme and multiple meanings from news, updates, and software delivery/deployment down the anchor chain to being a central point/center of where you go to have a look) 
- **solutiser** (sol theme, get a solution for your problem)
- **emporium/emporion** (trading place)
- **shannon** (nautical theme, homage to father of information theory, longest river in Ireland, symbol for continuity, flow, speed, deployments and downloads)
- **solex** (the rolex of software centers)
- **admiralty** (nautical theme, linguistic affinity to 'admire' and a nice HK vibe, the central business district to make the software-center future-proof)
- **galaxy** (avian theme, gravitationally bound system of software stars aka best in class software and components orbiting the Solus sphere)
- **solar** (avian theme, sun, access to the center of the solus system)

I have plenty of other awesome names somewhere written on a piece of paper in case these don't make the shortlist.
