### ISSUE TITLE
Add option to disable screenshots

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#109]
It would be great to have an option to disable screenshots in the _Settings_ or alternatively, to move them to a _Screenshots_ tab, so they are only loaded when clicked but not by default.

**Comment by ikeydoherty** [comment]
This seems kinda silly by me. If you're browsing a software center, the expectation is that you're going to consume bandwidth by installing things.. which download files ..

**Comment by baimafeima** [comment]
Especially when there are several screenshots, it takes up to 10 seconds to load for me.

**Comment by ikeydoherty** [comment]
I can't see how it slows it down, you can just navigate to a different page. The image fetching is done entirely in parallel and has a queue system.

**Comment by ikeydoherty** [comment]
Sod it - approving it. Bandwidth should be the users discretion, not ours.

**Comment by kyrios123** [comment]
@ikeydoherty it would be nice to disable screenshots when there is no internet connection otherwise it loads forever !

**Comment by baimafeima** [comment]
@ikeydoherty Thanks a lot for implementing this. I still think that a separate _Screenshot_ tab is a better solution as otherwise users will only see the image replacement "No screenshots available" which doesn't look very pleasing to the eye.
