### ISSUE TITLE
Add a button to launch the installed app.

### ISSUE THREAD

**Issue by SkyzohKey** [solus-project/solus-sc#110]
Before the `Uninstall` button it would be cool to have a button `Launch`, would allow the user to easily start the new app they just downloaded.

In term of UX, it's a sort of recompense for the user as it waited the app to install, showing a Launch button allows the user to be more "happy" about installing stuffs c:

**Comment by baimafeima** [comment]
Related: #33

**Comment by ikeydoherty** [comment]
Closing as dupe, thanks @baimafeima
