### ISSUE TITLE
Enable keyboard-driven navigation

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#130]
It would be great to be able to navigate solus-sc only via keyboard. In fact, I think it would greatly increase accessiblity (meant in the broadest sense of the word) for all Solus user-facing applications to support both mouse-driven and keyboard-driven navigation.

**Comment by kacperski1** [comment]
Seconding this. The main issue right now is that it's impossible to go back to the Search screen by using backspace (or any other button) - the only way is to click the back button with a mouse.

**Comment by retiform** [comment]
Other issues include, that once on the search tab, users are stuck there without use of mouse.  Additionally, on the home screen, each category can be selected with the keyboard, but the boarder can also be selected, leading to confusing behavior.

**Comment by kmandarin-orange** [comment]
Agreed, any screen with a useable back button should be able to be left with a backspace and/or alt-left arrow, similar to browser shortcuts. That should make the workflow more seamless between commonly-used apps.

**Comment by JoshStrobl** [comment]
You're necroing an issue from 2 years ago on an org that is no longer used. Should be at https://github.com/getsolus/solus-sc and keyboard navigation is already planned and approved, so really no need to necro.

**Comment by kmandarin-orange** [comment]
My bad, I was under the impression this was the correct repository since this is in the main Solus Project github page.

**Comment by JoshStrobl** [comment]
The main GitHub org is the GetSolus org. Been this way since [October 2018](https://getsol.us/2018/10/27/in-full-sail/).
