### ISSUE TITLE
Security updates available.... or not !

### ISSUE THREAD

**Issue by kyrios123** [solus-project/solus-sc#138]
Well I guess there are security updates available but probably not for any of the installed packages...
![security-updates](https://user-images.githubusercontent.com/7815316/29083215-3a13e4fa-7c68-11e7-92c0-ac8ea4e8eb6b.png)

**Comment by ikeydoherty** [comment]
Look at `ca-certs`, it was a security update. It's also in `Required Updates` because it's a mandatory update (`system.base`) - so yeah, it's actually telling the truth :)

**Comment by kyrios123** [comment]
Okay, got it, thanks!
