### ISSUE TITLE
Update Details tab doesn't respect indented bullet points

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solus-sc#145]
**Phab:** 
![screenshot from 2017-09-18 08 48 57](https://user-images.githubusercontent.com/1370117/30525848-41d473fc-9c4e-11e7-893e-2d07dc66579e.png)

**Software Center:**
![screenshot from 2017-09-18 08 49 44](https://user-images.githubusercontent.com/1370117/30525851-55edc848-9c4e-11e7-823e-de05cbca80ce.png)

**Commit:**
`commit 919bb09874a5bf204ca45b2690b77e94e691e35a (HEAD -> master, tag: micro-1.3.2-9, origin/master, origin/HEAD)
Author: Justin Zobel <justin@solus-project.com>
Date:   Sun Sep 17 15:58:45 2017 +0930

    Update micro to 1.3.2
    
    **Changelog:**
    
    - Add support for crlf and lf
    - Lua now has access to most of the Go standard library
    - Simply import go packages: local `fmt = import("fmt")`
    - Syntax highlighting
     - Julia support
     - Improved yaml highlighting
    - Bug fixes for multiple cursors
    - Bug fixes for undo/redo
    - Add a new `--config-dir` option to set a custom location for the configuration directory
`

**Comment by ikeydoherty** [comment]
We'll never see those as we have to strip the start of the string. We know how to handle " *" and "*", yours is using both.

**Comment by ikeydoherty** [comment]
and fuck github for eating my `*`

**Comment by ikeydoherty** [comment]
Fuck sake. Well, one has one space and the other has two. I can't make it show up. Feckin markdown.

**Comment by Justinzobel** [comment]
No worries, I'll find another solution.
