### ISSUE TITLE
Internet drops

### ISSUE THREAD

**Issue by cybermails** [solus-project/solus-sc#147]
I've noticed that every once in a while (an hour or less) I have random internet drops without any prior notice. I'm hardwired to the computer I'm using Solus Budgie on. My Wifi seems to working just fine during that time. The Ethernet network icon in the system tray would show that it is connected but I don't have any internet connectivity. The only solution is to 'Disconnect' and reconnect and then everything works normally. I'm 90% sure this is something to do with the operating system. Any thoughts on how I can diagnose this further to pinpoint the problem?

**Comment by ikeydoherty** [comment]
Sorry but I'm gonna have to ask you open this issue up on https://dev.solus-project.com/ so it can be tracked - this repository is for the software center, and wouldn't be where the issue would lie.
