### ISSUE TITLE
Add link to GitHub/upstream where available

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#149]
In order to more quickly follow up with issues identified as upstream issues, I'd recommend to add a link to the issue trackers of the respective projects. I remember this feature to be available in the new elementary OS app center and liked the efficiency.

**Comment by ikeydoherty** [comment]
We already show links for the home page and issue tracker when they're in the AppStream data.

**Comment by baimafeima** [comment]
I know there is a button linking to the home page but I didn't find separate links to the issue tracker when checking several projects in the software center.
