### ISSUE TITLE
Display error messages / Can't update python-psutil

### ISSUE THREAD

**Issue by nextgensparx** [solus-project/solus-sc#165]
The Software Center was telling me to update python-psutil but when I tried to, nothing happened.

I tried uninstalling it and then reinstalling it but then found I could no longer install it at all. I then tried installing it using eopkg and that gave the error: 

> [Errno 21] Is a directory: 'usr/lib/python2.7/site-packages/psutil-5.4.1-py2.7.egg-info'

After deleting the folder mentioned above, the issue was resolved.

I am not sure why this error occurred, but it would be great if the Software Center showed the error message when trying to update rather than doing nothing.

**Comment by ikeydoherty** [comment]
Agreed - but it does look like you manually installed that with pip

**Comment by nextgensparx** [comment]
Woops xD. Would it not be better for it to just overwrite the existing one? I don't entirely understand how eopkg installs it.

**Comment by ikeydoherty** [comment]
I've solved the underlying error here: https://github.com/solus-project/package-management/commit/3e0f6cb81a320532312fbe5233bf21648b043ecb

eopkg will now just wipe out the dirty pip tree when installing a package that conflicts with it
