### ISSUE TITLE
Allow Terminal in Software Center

### ISSUE THREAD

**Issue by boustanihani** [solus-project/solus-sc#179]
Please allow the user to see the terminal output when installing packages through the software center.

Another issue, when installation starts, the progress is at the very bottom of the software center and one may not notice this, the installation progress should be made more visible to the user.

**Comment by ikeydoherty** [comment]
The Software Center doesn't execute anything via a terminal, so it wouldn't have anything to show. Everything is done over D-BUS, there is no private process on a pty we can show, sorry.

The progressbar stuff is changing for the next iteration though :)

**Comment by boustanihani** [comment]
okay thanks :)
