### ISSUE TITLE
Check for updates status message

### ISSUE THREAD

**Issue by saras12** [solus-project/solus-sc#18]
On clicking 'Check for updates' in the Software Center, it shows a message 'Discombobulating update matrix'. It would be good to have a user friendly message. Maybe something like 'Checking for updates'.

**Comment by ikeydoherty** [comment]
Do you have evidence of a usability issue for this passive control?

**Comment by saras12** [comment]
Basically, as a first time user of Solus, I am not sure what the message means. When I click on 'Check for updates', it feels like it is doing something else (maybe because of my lack of familiarity). It might have helped if the feedback message was kept simple considering new users.

**Comment by ikeydoherty** [comment]
It's just an example of a humorous progress message, a long standing practice, to bring some form of light to the users day while waiting on a task (there are more)

**Comment by ikeydoherty** [comment]
On further analysis of the issue, it occurs to me the perma-statusbar makes it very clear what is happening, and these progress views are entirely contextual (After clicking on a certain action) - so there is no scope for confusion
