### ISSUE TITLE
The New In-Development Solus-SC Fails to Render Properly With Some(?) Themes

### ISSUE THREAD

**Issue by moriel5** [solus-project/solus-sc#190]
I had tested this with the Arc variants and with the basic Adwaita themes (Adwaita, High Contrast, etc.), and this issue only appeared for me on the Arc variants, although it may also appear with other themes.
![screenshot from 2018-03-13 12 36 47](https://user-images.githubusercontent.com/20175297/37396089-93e2e6fc-2780-11e8-83b0-faeded809070.png)

**Comment by ikeydoherty** [comment]
Yeah this is fixed on master now as we were still applying the old Arc workarounds :)
