### ISSUE TITLE
Include log data

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solus-sc#20]
Solus SC should create a log when doing things so we can see if something broke while updating (this just happened in irc). That way we can ask for logs if people have issues.
##

**Comment by ikeydoherty** [comment]
? Use eopkg history

**Comment by Justinzobel** [comment]
Aren't we aiming to not have to use the terminal? It could just be that info but put into SC so it's neat and tidy for end users.

**Comment by ikeydoherty** [comment]
Sure, neat and tidy, and they still won't understand it. Why duplicate an *already existing* log file?

**Comment by Justinzobel** [comment]
Software Center as an app could have it's own log file to see where things
happened etc, above and beyond the package history/actions.

**Comment by ikeydoherty** [comment]
Well there is nothing "above and beyond" those, because those are handled by the backend, not the frontend ..

**Comment by baimafeima** [comment]
How about a _Copy Log Data_ button which copies log data to the clipboard. This information can then easily pasted for further analysis.

**Comment by ikeydoherty** [comment]
There isn't a per package log. There is a global log file for all transactions. I don't see this issue as relevant any more given the changes in CI practices and the expectation that devs test their own upgrade paths for their eopkgs in Solus
