### ISSUE TITLE
Packages installed with solus-sc don't have the same behavior as the ones installed with eopkg

### ISSUE THREAD

**Issue by nathanielsimard** [solus-project/solus-sc#202]
When removing a package installed with `solus-sc` that has dependencies, then `eopkg rmo` won't remove its dependencies. If the package was installed with `eopkg`, then remove orphaned packages would work.

**Comment by ikeydoherty** [comment]
Yea I'm aware of this one, we fixed it in `master` so that orphan state is respected. I know its not released yet but as the work is done I'll mark it fixed
