### ISSUE TITLE
Create snapd and flatpak plugins for new solus-sc modular approach

### ISSUE THREAD

**Issue by sirredbeard** [solus-project/solus-sc#209]
In addition to the eopkg plugin, plugins for snapd and flatpak should also be developed.

These could be similar to how gnome-software-plugin-snap adds snap support to gnome-software.

The plugin API in solus-sc should be flexible enough that future plugins could be written to support other packaging approaches, even the possibility of a plugin for another distro repos.

**Comment by JoshStrobl** [comment]
But...we're already doing this in the upcoming release. See `xng/plugins`.
