### ISSUE TITLE
headerbar issue

### ISSUE THREAD

**Issue by bobblkabb** [solus-project/solus-sc#227]
On my plasma installation I put close/min/max on the left side. 
Unfortunately Software-Center still have those buttons on the right side.

I made a report on KDE and they say it's a gtk headerbar issue:
[https://bugs.kde.org/show_bug.cgi?id=399866](url)

Any chance to change the Software-Center app?

**Comment by JoshStrobl** [comment]
> Any chance to change the Software-Center app?

At this moment, we have no plans to change away from the use of the Headerbar, both for the current SC as well as the one which resides in xng/
