### ISSUE TITLE
Add cancel install feature 

### ISSUE THREAD

**Issue by ghost** [solus-project/solus-sc#228]
I clicked install on a program i didn't mean to install and it included over 70 dependencies which i cannot even think of hunting down and removing manually after it is installed with no option to cancel the install before the download completes.

**Comment by JoshStrobl** [comment]
Issues should be filed at https://github.com/getsolus/solus-sc

Furthermore: We have a rollback feature with eopkg. See https://getsol.us/articles/package-management/history-and-rollback/en/
