### ISSUE TITLE
Cant run "shared library" files?

### ISSUE THREAD

**Issue by ghost** [solus-project/solus-sc#232]
Hi, I'm trying to run this crypto wallet (https://github.com/ConcealNetwork/conceal-desktop/releases) the ubuntu 1804 release file. When trying to run it on solus I get an error saying there is no application installed for "shared library" files. What does this mean? I know this file can be run outside of ubuntu because I ran it on Manjaro and other distro's no problem. It launched just liike an appimage would.

Any ideas on this one?

**Comment by DataDrake** [comment]
This is not the right bug tracker for reporting these issues.
