### ISSUE TITLE
Show also dependancies' sizes

### ISSUE THREAD

**Issue by goldencut** [solus-project/solus-sc#238]
When installing a package its 'Installed size' is shown but AFAIU it only indicates the package itself, without packages it depends on that also need to be installed, hence it's impossible to evaluate the actual disk space cost of installing the package. It would be very useful when installing a package and the dependencies are shown to also show their installed sizes.

**Comment by JoshStrobl** [comment]
1. Wrong organization. Should be over at the GetSolus org.
2. Current Software Center will not be seeing any work and is pending a full rewrite.
