### ISSUE TITLE
Ensure URLs are clickable within the Update Details View

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solus-sc#25]
Create links of URLs in Update Details "Changes" box so they can be clicked and opened in the default browser.
![screenshot from 2016-09-11 14-19-10](https://cloud.githubusercontent.com/assets/1370117/18415252/0ec619ae-782b-11e6-8924-a797c74b4fa0.png)
##

**Comment by ikeydoherty** [comment]
You want to put links to changelogs inside changelogs? What?

**Comment by Justinzobel** [comment]
Yes.

**Comment by ikeydoherty** [comment]
Ew

**Comment by ikeydoherty** [comment]
OK more awake now. So is this just generally make-URLS-clickable? Cuz there are probably multiple use cases right?

**Comment by Justinzobel** [comment]
LOL helps being awake to not dismiss great ideas :P

**Comment by ikeydoherty** [comment]
Welcome to the life of Ikey. :p
