### ISSUE TITLE
On i3, clicking "Install" does not prompt for root password, and then does not install the package.

### ISSUE THREAD

**Issue by kminehart** [solus-project/solus-sc#26]
Using the command line install, `sudo eopkg install <name>` works fine.  I'll try running solus-sc from the terminal and see if I can get any extra debug info, but so far it's been nothing.

Sometimes it will work, but after working at least once, closing the application, then reopening it, it will cease to function properly.
##

**Comment by ikeydoherty** [comment]
This isn't a Solus SC bug, you need a polkit agent running.

**Comment by ikeydoherty** [comment]
Do you have polkit-gnome.. ?

**Comment by kminehart** [comment]
Yes I have polkit-gnome installed.

```
[N] ⋊> ~ eopkg list-installed | grep polkit                            
polkit                           - Application-level authorization toolkit
polkit-devel                     - Development files for polkit
polkit-gnome                     - GNOME Polkit Authentication Agent
```

It's not running though, and obviously it should be.  It works perfectly on Budgie, but only once per i3 session

**Comment by ikeydoherty** [comment]
OK but thats i3 specific you'll need to add to autostart :)
