### ISSUE TITLE
Help with translations

### ISSUE THREAD

**Issue by LaurentTreguier** [solus-project/solus-sc#37]
For now only the `en_GB` locale is the only one. Is there any specific way to help with translations ? I'd love to help with some French translations (as I am French).

**Comment by ikeydoherty** [comment]
Yeah I haven't finished getting everything translatable here yet but if you wanna jump in early then please do :D 

https://www.transifex.com/solus-project/solus-sc/

**Comment by LaurentTreguier** [comment]
Then it will be my pleasure to help !
