### ISSUE TITLE
SC gets stuck when performing package updates

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/solus-sc#43]
I'm using the unstable repository. Solus-sc gets repeatedly stuck at the _Upgraded {} of {}_ and _Please check back later, updates are now applying..._ messages at every package update. The operation does finish in the background...

This is all I get in the terminal:

> blaz@nanoftw ~ $ solus-sc
> /usr/bin/solus-sc:25: Warning: g_source_unref: assertion 'source != NULL' failed
>   app.run(sys.argv)

![screenshot from 2016-11-15 09-03-02](https://cloud.githubusercontent.com/assets/6306479/20297807/ac949574-ab12-11e6-8da4-0e35bcd29a16.png)

**Comment by bmeznarsic** [comment]
Also. I have no issues when using eopkg upgrade.

**Comment by bmeznarsic** [comment]
Issue fixed for me in https://git.solus-project.com/packages/pisi/commit/?h=pisi-3.3-62&id=43151918f8ad8227b948be47192835f7f0fd86c3

**Comment by ikeydoherty** [comment]
Ta :)

**Comment by Daeon88** [comment]
I'm experiencing the same issue with Solus 4 in a Ryzen desktop. Eopkg goes fine by the way. Any clue?
