### ISSUE TITLE
Replace Installed by Statistics tab

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#48]
I think the _Installed_ tab has potential for more. At the moment it only lists all packages which are currently installed on the system. Why not rename it to _Statistics_ and add more information to it such as:

- a visual diagram of all packages separated into core and system packages, applications and their dependencies
- a distinction between list view, grid view and diagrams
- the total number and size of installed packages
- the total number and size of available packages in the repository
- a percentage of FOSS software packages and proprietary software packages currently installed on the machine
- a button to show all currently active system processes and actively loaded packages
- time stamps to indicate when software packages were installed for the _first_ time, and updated and launched for the _last_ time to inform users about potentially dormant packages
- what applications are most used (similar to the ranking in the Budgie menu)

**Comment by ikeydoherty** [comment]
Bloat. Nope. Focusing on "packages" not "software".

> a percentage of FOSS software packages and proprietary software packages currently installed on the machine

Come now, this isn't Debian.

**Comment by baimafeima** [comment]
> Come now, this isn't Debian.

I like that part about Debian, not their outdated repositories though.

> Bloat.

I would call it polish. I don't like bloat either. Depends on how it would be implemented. As long as it generates valuable information, doesn't slow down the Software Center, and doesn't clutter the inferface, why not?

**Comment by ikeydoherty** [comment]
Why is it valuable? This is what I don't get. Valuable to who? Users use the software center to discover and install software, not to be overwhelmed with social movements and political agenda

**Comment by baimafeima** [comment]
> social movements and political agenda

Now I've lost you. What do you mean? I am not talking about _politics_ but about _transparency_ towards the user, of me knowing what is on the machine. To be clear, I am guided by two kind of values: transparency and privacy. If I use any kind of software or a distribution or an operating system, I ask myself: how transparent are they with what they do and how much privacy do I have when using it?
