### ISSUE TITLE
Move current Home to Repository and redesign new Home

### ISSUE THREAD

**Issue by baimafeima** [solus-project/solus-sc#49]
I know that at the moment the _Home_ tab is essentially like a _Repository_ tab. It only refers to what can be installed from the Solus repository, not to any other information. Why not simply name it _Repository_ then? I feel this would be a more consistent naming policy as there is already a _Third Party_ tab which (temporarily) complements it. This will free up space for a more broadly conceived _new Home_ tab which could contain short and precise (no lengthy wiki) information about:
- Solus packaging philosophy, policy and procedure to provide a carefully curated, up to date, and best in class software selection (as opposed to Archs "pack it all" and Debians "let it rot")
- the repo layout and the third party section
- how to get involved with packaging
- where to go in case a particular package is missing and to have it evaluated for possible inclusion
- an emergency button to reveal contact information in terms of security issues which require immediate attention and are better not communicated through public channels like Phabricator

Lastly, a _Home_ tab should make a user _feel at home_ and as the Software Center is such an important component of the entire user experience, it should ideally provide information to familiarize oneself in Solus land. I cannot think of a better place than to realize this in the Software Center.

**Comment by ikeydoherty** [comment]
Oh no no no no. This is a user facing tool, not a developer tool. "Repository" != "Home" or "Apps" or "Software" or "Available".

Packaging policy? Packaging docs? These have no business being in a software center. We have a wiki for this. We make a stern point in not even mentioning "Package" anywhere.

**Comment by baimafeima** [comment]
> Packaging policy? Packaging docs? These have no business being in a software center. We have a wiki for this.

I am talking about maximum one, two or three sentences, not more. The rest should absolutely go into a wiki. 

> This is a user facing tool, not a developer tool. 

I don't see how my suggestions can be interpreted as making it a developer tool. They are simply meant to do two things: increase transparency and user satisfaction. If I start up the Software Center for the first time and don't find the software I need, a simply look at the _Home_ tab would reveal where and how I can get involved, either with packaging or with requesting a package. This could be implemented with one or two sentences, a nice button which links to Phabricator, and that's it. Think about it in terms of a _quick guide_ like those you find when you are in a good hotel and it shows you what number to dial if you need this and that, where to dry-clean your suit, on which floor the hair dresser is, and so on.

**Comment by baimafeima** [comment]
For future reference: https://www.omgubuntu.co.uk/2018/09/canonical-wants-to-make-its-software-center-more-like-the-apple-app-store
Ubuntu seems to have plans for redesigning the "home" tab by introducing editorial content.
