### ISSUE TITLE
Update issue total package count calculation

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solus-sc#52]
New install today and updated straight off the bat and got "Upgraded 91 of 89"

**Comment by ikeydoherty** [comment]
Which is fixed by the update itself, to the best of my knowledge

**Comment by Justinzobel** [comment]
Ah I'll look for next update and see if it happens again.

**Comment by ikeydoherty** [comment]
I didn't close this because there is still a possibility it exists fwiw
