### ISSUE TITLE
Add a statusbar message for updates

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solus-sc#6]
On launch while it's updating repository db in background, display information in the statusbar like when installing/upgrading packages. It will at least let the user know it's happening and when it's finished display a notification with "no updates found" or "x updates found."
##

**Comment by ikeydoherty** [comment]
Just.. for reference, it's not a status bar :) But yes I agree we should let folks know something is going on.

**Comment by ikeydoherty** [comment]
We have status stuff in now
