### ISSUE TITLE
eopkg manager new line issues.

### ISSUE THREAD

**Issue by mitchellurgero** [solus-project/solus-sc#60]
Dont have a lot of time, see screenshot.
This is installing a large file and eventually it looks like terminal starts to ignore the new lines. (Or eopkg just stops using them)
![screenshot from 2017-01-04 15-29-29](https://cloud.githubusercontent.com/assets/4168998/21659978/d44cac4e-d292-11e6-9c5f-217758e0ed4c.png)

**Comment by ikeydoherty** [comment]
This is a terminal emulator issue (incorrect shell or mode) as eopkg uses `\r`
