### ISSUE TITLE
[Request] KiCad

### ISSUE THREAD

**Issue by cybernet** [solus-project/solus-sc#7]
KiCad is a set of applications used to capture electronic schematics and design printed circuit boards. KiCad runs on Windows, Linux, and Apple OSX and is released under the open source GNU GPL.

It is used by many thousands of hobbyist (and professional) around the world.
It is available for all the major distros except Solus ;) 
See also http://kicad-pcb.org/download/

The normal install process is to download the source and compile locally (even under windows)...

It might be a good candidate for another "how to" package video... 

Mike

PS, I hope to hell I'm doing this right, this is a request not a bug report but I've been directed here so I guess it's the right place...

[ REPOSTED FROM BUG TRACKER ]
https://bugs.solus-project.com/show_bug.cgi?id=847

**Comment by ikeydoherty** [comment]
This repository is for  the graphical software manager. I see nothing to indicate you were directed here. I'll handle this on our own bugzilla instance.
