### ISSUE TITLE
Flash Player isn't available anymore?

### ISSUE THREAD

**Issue by Vistaus** [solus-project/solus-sc#84]
I'm getting an error whilst trying to update Flash Player. See screenshot.
![screenshot from 2017-04-12 10 50 07](https://cloud.githubusercontent.com/assets/1716229/24949427/d3b5501a-1f6d-11e7-88c9-2897f9c16553.png)

**Comment by n0rse** [comment]
@Vistaus flash player is working now. If it stops working, or any 3rd-party software stops working just submit an issue to https://dev.solus-project.com/ :). Also, my.. eyes.. has to be the whitest desktop out there
