### ISSUE TITLE
Search needs some improvements

### ISSUE THREAD

**Issue by philipzae** [solus-project/solus-sc#94]
So i was testing out the search results in Software Center and saw some flaws

1) I searched for 'gnome boxes' and it didnt show any results, but if you open up the info page for gnome-boxes, it shows 'GNOME Boxes' as the name of the package

2) I searched for 'virtual machine' and gnome-boxes didnt show in the results, though its summary and full description have both words in it

**Comment by baimafeima** [comment]
Related: https://dev.solus-project.com/T2762

**Comment by ikeydoherty** [comment]
You can now search for "GNOME Boxes". Note that currently the search is against the **eopkg summary** - which currently disagrees with the AppStream summary. The remaining fault is to
fix the GNOME Boxes package to say "virtual machines" in the summary, not "virtual systems" :)

![screenshot from 2017-05-15 01-18-21](https://cloud.githubusercontent.com/assets/164489/26038999/9c4e8534-390c-11e7-9c0b-f17fac4a770f.png)

**Comment by philipzae** [comment]
If the search can only search through the eopkg summary (which is quite short) or the AppStream summary (which is normally alot longer), ideally it should search through the AppStream summary as it would have more keys that search queries could hit against.

**Comment by kyrios123** [comment]
Search `WultiWriter` does not work although it is the name displayed on the SC.
You have to search on `multi-writer` to find it.

Sorry.. today I comment on closed issues only :P

**Comment by ikeydoherty** [comment]
I would be very surprised if it found `WultiWriter`
