### ISSUE TITLE
Question marks appearing instead of apostrophes in update log

### ISSUE THREAD

**Issue by philipzae** [solus-project/solus-sc#95]
![apostraphy appearing as question marks](https://cloud.githubusercontent.com/assets/4412114/25590333/37f8daa8-2ec1-11e7-8443-26f9f2a45e36.png)

**Comment by philipzae** [comment]
Also noticed that ampersands appear as '&amp;' like in the wine package description.

**Comment by ikeydoherty** [comment]
Got a fix

![screenshot from 2017-05-12 06-53-38](https://cloud.githubusercontent.com/assets/164489/25983987/e0c7c6fa-36df-11e7-869b-ef6fd74e60ce.png)

**Comment by ikeydoherty** [comment]
Fixed in solbuild, but for the affected packages they'll require rebuilds
